source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem "beaker-hostgenerator", "~> 0.2"
gem "beaker", '~> 2.5'
if ENV["BEAKER_TYPE"] == 'pe'
  gem 'beaker-pe', '~> 0.9'
  gem 'scooter', '~> 3.2', :require => false
end
gem 'rake', "~> 10.1"
gem 'rototiller', '= 0.1.0'

if File.exists? "#{__FILE__}.local"
    eval(File.read("#{__FILE__}.local"), binding)
end
