require 'rake/clean'
require 'rototiller'

desc 'Run acceptance tests'

desc "Generate Beaker Host config"
task :host_config do
  if ENV["BEAKER_CONFIG"]
    next
  end
  if not ENV['TEST_TARGET']
    fail "FATAL: must set TEST_TARGET environment variable."
  end

  generate = "bundle exec beaker-hostgenerator"
  generate += " --disable-default-role #{ENV['TEST_TARGET']}"
  generate += " > hosts.cfg"
  sh generate
  sh "cat hosts.cfg"
end

desc 'Check the redis version if Jenkins'
task :check_redis_pe_ver do
  if ENV['JENKINS_HOME']
    if !ENV['BEAKER_PE_VER']
      ENV['BEAKER_PE_VER'] = `redis-cli -h redis.delivery.puppetlabs.net get 2016.3_pe_version`.strip
    else
      warn 'BEAKER_PE_VER already set, skipping check with redis'
    end
  end
end

desc "Run beaker based acceptance tests"
task acceptance: :host_config
task acceptance: :check_redis_pe_ver if ENV["BEAKER_TYPE"] == 'pe'
task :acceptance do

  #fail if SHA not present
  fail "SHA must be set in order to setup repositories!!!" if !ENV['SHA']

  # hardcode the pe_dir into the repo instead of the jenkins job
  ENV['BEAKER_PE_DIR'] = 'http://neptune.puppetlabs.lan/2016.3/ci-ready' if ENV["BEAKER_TYPE"] == 'pe'

  config = ENV["BEAKER_CONFIG"] || 'hosts.cfg'
  preserve_hosts = ENV["BEAKER_PRESERVEHOSTS"] || 'onfail'
  type = ENV["BEAKER_TYPE"] || 'foss'
  keyfile = ENV["BEAKER_KEYFILE"] || "#{ENV['HOME']}/.ssh/id_rsa-acceptance"
  options_file = ENV["BEAKER_OPTIONSFILE"] || ''
  test_suite = ENV["BEAKER_TESTSUITE"] || 'tests/'
  load_path = ENV["BEAKER_LOADPATH"] || ''
  pre_suite = ENV["BEAKER_PRESUITE"] || "setup/#{type}/pre_suite"
  helper = ENV["BEAKER_HELPER"] || ''
  post_suite = ENV["BEAKER_POSTSUITE"] || ''
  opts = ENV["BEAKER_OPTS"] || ''

  beaker = "bundle exec beaker "
  beaker += " --xml"
  beaker += " --debug"
  beaker += " --no-color"
  beaker += " --repo-proxy"
  beaker += " --preserve-hosts #{preserve_hosts}" if preserve_hosts != ''
  beaker += " --config #{config}" if config != ''
  beaker += " --helper #{helper}" if helper != ''
  beaker += " --type #{type}" if type != ''
  beaker += " --keyfile #{keyfile}" if keyfile != ''
  beaker += " --options-file #{options_file}" if options_file != ''
  beaker += " --load-path #{load_path}" if load_path != ''
  beaker += " --pre-suite #{pre_suite}" if pre_suite != ''
  beaker += " --post-suite #{post_suite}" if post_suite != ''
  beaker += " --tests #{test_suite}" if test_suite != ''
  beaker += " #{opts}" if opts != ''
  sh beaker
end

namespace :ci do
  namespace :test do

    desc 'This task is used by CI to test the package pe-client-tools'
    rototiller_task :package => [:set_test_target]do |t|

      flags = [
          {:name => '--xml', :is_boolean => true},
          {:name => '--no-color', :is_boolean => true},
          {:name => '--debug', :is_boolean => true},
          {:name => '--hosts', :override_env => 'TEST_TARGET'},
          {:name => '--helper', :default => 'helper.rb'},
          {:name => '--keyfile', :default => "#{ENV['HOME']}/.ssh/id_rsa-acceptance", :override_env => 'BEAKER_KEYFILE'},
          {:name => '--load-path', :default => 'lib', :override_env => 'BEAKER_LOADPATH'},
          {:name => '--pre-suite', :default => 'setup/pe/pre_suite', :override_env => 'BEAKER_PRESUITE'},
          {:name => '--tests', :default => 'pe/tests', :override_env => 'BEAKER_TESTSUITE'},
          {:name => '--preserve-hosts', :default => 'onfail', :override_env => 'BEAKER_PRESERVEHOSTS'},
      ]

      t.add_flag(*flags)

      t.add_env(:name => 'SHA',           :message => 'The sha for pe-client-tools')
      t.add_env(:name => 'SUITE_VERSION', :message => 'The suite version used by Jenkins')

      t.add_env do |env|
        env.name = 'pe_dist_dir'
        env.message = 'The location to download PE from example "http://neptune.puppetlabs.lan/20XX.X/ci-ready"'
        env.default = 'http://neptune.puppetlabs.lan/2016.3/ci-ready'
      end

      t.add_command({:name => 'beaker', :override_env => 'BEAKER_EXECUTABLE'})
    end

    task :set_test_target do
      client = ENV['CLIENT_TEST_TARGET'] || (fail 'The environment variable CLIENT_TEST_TARGET must be set.')
      # process the CLIENT_TEST_TARGET variable and assign it to TEST_TARGET so that rototiller will pick it up
      monolithic_config = "#{client}client.mdca"
      master_agent_config = "centos7-64.mdca-#{client}client.a"
      ENV['TEST_TARGET'] ||= (client =~ /win|osx/) ? master_agent_config : monolithic_config
    end

  end
end

