// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetQueryParams creates a new GetQueryParams object
// with the default values initialized.
func NewGetQueryParams() *GetQueryParams {
	var ()
	return &GetQueryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetQueryParamsWithTimeout creates a new GetQueryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetQueryParamsWithTimeout(timeout time.Duration) *GetQueryParams {
	var ()
	return &GetQueryParams{

		timeout: timeout,
	}
}

// NewGetQueryParamsWithContext creates a new GetQueryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetQueryParamsWithContext(ctx context.Context) *GetQueryParams {
	var ()
	return &GetQueryParams{

		Context: ctx,
	}
}

// NewGetQueryParamsWithHTTPClient creates a new GetQueryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetQueryParamsWithHTTPClient(client *http.Client) *GetQueryParams {
	var ()
	return &GetQueryParams{
		HTTPClient: client,
	}
}

/*GetQueryParams contains all the parameters to send to the API endpoint
for the get query operation typically these are written to a http.Request
*/
type GetQueryParams struct {

	/*Query*/
	Query *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get query params
func (o *GetQueryParams) WithTimeout(timeout time.Duration) *GetQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get query params
func (o *GetQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get query params
func (o *GetQueryParams) WithContext(ctx context.Context) *GetQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get query params
func (o *GetQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get query params
func (o *GetQueryParams) WithHTTPClient(client *http.Client) *GetQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get query params
func (o *GetQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the get query params
func (o *GetQueryParams) WithQuery(query *string) *GetQueryParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the get query params
func (o *GetQueryParams) SetQuery(query *string) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *GetQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Query != nil {

		// query param query
		var qrQuery string
		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {
			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
