// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/puppetlabs/puppetdb-cli/api/models"
)

// GetExportReader is a Reader for the GetExport structure.
type GetExportReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExportOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetExportDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetExportOK creates a GetExportOK with default headers values
func NewGetExportOK(writer io.Writer) *GetExportOK {
	return &GetExportOK{
		Payload: writer,
	}
}

/*GetExportOK handles this case with default header values.

returns gzipped archive of puppetdb data
*/
type GetExportOK struct {
	Payload io.Writer
}

func (o *GetExportOK) Error() string {
	return fmt.Sprintf("[GET /pdb/admin/v1/archive][%d] getExportOK  %+v", 200, o.Payload)
}

func (o *GetExportOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetExportDefault creates a GetExportDefault with default headers values
func NewGetExportDefault(code int) *GetExportDefault {
	return &GetExportDefault{
		_statusCode: code,
	}
}

/*GetExportDefault handles this case with default header values.

Unexpected error
*/
type GetExportDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get export default response
func (o *GetExportDefault) Code() int {
	return o._statusCode
}

func (o *GetExportDefault) Error() string {
	return fmt.Sprintf("[GET /pdb/admin/v1/archive][%d] getExport default  %+v", o._statusCode, o.Payload)
}

func (o *GetExportDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetExportDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
