// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetExportParams creates a new GetExportParams object
// with the default values initialized.
func NewGetExportParams() *GetExportParams {
	var ()
	return &GetExportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetExportParamsWithTimeout creates a new GetExportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetExportParamsWithTimeout(timeout time.Duration) *GetExportParams {
	var ()
	return &GetExportParams{

		timeout: timeout,
	}
}

// NewGetExportParamsWithContext creates a new GetExportParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetExportParamsWithContext(ctx context.Context) *GetExportParams {
	var ()
	return &GetExportParams{

		Context: ctx,
	}
}

// NewGetExportParamsWithHTTPClient creates a new GetExportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetExportParamsWithHTTPClient(client *http.Client) *GetExportParams {
	var ()
	return &GetExportParams{
		HTTPClient: client,
	}
}

/*GetExportParams contains all the parameters to send to the API endpoint
for the get export operation typically these are written to a http.Request
*/
type GetExportParams struct {

	/*AnonymizationProfile*/
	AnonymizationProfile *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get export params
func (o *GetExportParams) WithTimeout(timeout time.Duration) *GetExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get export params
func (o *GetExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get export params
func (o *GetExportParams) WithContext(ctx context.Context) *GetExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get export params
func (o *GetExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get export params
func (o *GetExportParams) WithHTTPClient(client *http.Client) *GetExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get export params
func (o *GetExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAnonymizationProfile adds the anonymizationProfile to the get export params
func (o *GetExportParams) WithAnonymizationProfile(anonymizationProfile *string) *GetExportParams {
	o.SetAnonymizationProfile(anonymizationProfile)
	return o
}

// SetAnonymizationProfile adds the anonymizationProfile to the get export params
func (o *GetExportParams) SetAnonymizationProfile(anonymizationProfile *string) {
	o.AnonymizationProfile = anonymizationProfile
}

// WriteToRequest writes these params to a swagger request
func (o *GetExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AnonymizationProfile != nil {

		// query param anonymization_profile
		var qrAnonymizationProfile string
		if o.AnonymizationProfile != nil {
			qrAnonymizationProfile = *o.AnonymizationProfile
		}
		qAnonymizationProfile := qrAnonymizationProfile
		if qAnonymizationProfile != "" {
			if err := r.SetQueryParam("anonymization_profile", qAnonymizationProfile); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
