// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/puppetlabs/puppetdb-cli/api/models"
)

// GetStatusReader is a Reader for the GetStatus structure.
type GetStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetStatusOK creates a GetStatusOK with default headers values
func NewGetStatusOK() *GetStatusOK {
	return &GetStatusOK{}
}

/*GetStatusOK handles this case with default header values.

returns trapperkeeper status of puppetdb
*/
type GetStatusOK struct {
	Payload interface{}
}

func (o *GetStatusOK) Error() string {
	return fmt.Sprintf("[GET /status/v1/services][%d] getStatusOK  %+v", 200, o.Payload)
}

func (o *GetStatusOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStatusDefault creates a GetStatusDefault with default headers values
func NewGetStatusDefault(code int) *GetStatusDefault {
	return &GetStatusDefault{
		_statusCode: code,
	}
}

/*GetStatusDefault handles this case with default header values.

Unexpected error
*/
type GetStatusDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get status default response
func (o *GetStatusDefault) Code() int {
	return o._statusCode
}

func (o *GetStatusDefault) Error() string {
	return fmt.Sprintf("[GET /status/v1/services][%d] getStatus default  %+v", o._statusCode, o.Payload)
}

func (o *GetStatusDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
