#!/bin/sh

set -o errexit

. make/include/colors

printf "%b==> Linting%b\n" "${OK_COLOR}" "${ERROR_COLOR}"

ISSUES=$(mktemp)

trap "cat ${ISSUES} ; rm -f ${ISSUES}" EXIT

golint \
  $(go list -f '{{ .Dir }}' ./...)  \
  >> "${ISSUES}"

printf "%b" "${NO_COLOR}"

test ! -s "${ISSUES}"
