#!/bin/sh

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. make/include/colors

printf "%b==> Generating mocks %b\n" "${OK_COLOR}" "${ERROR_COLOR}"

pushd token/testing && mockgen --source ../token.go --destination=token_mock.go && popd

printf "%b" "${NO_COLOR}"
