#!/bin/sh

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. make/include/colors

printf "%b==> Generating swagger client %b\n" "${OK_COLOR}" "${ERROR_COLOR}"

swagger generate client \
	--target=${GIT_ROOT}/api \
	--spec=${GIT_ROOT}/api/api.yaml \
	--name=puppetdb-cli

printf "%b" "${NO_COLOR}"
