#!/bin/sh

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}


. make/include/colors

printf "%b==> Vetting %b\n" "${OK_COLOR}" "${ERROR_COLOR}"

go vet $(go list -f '{{ .ImportPath }}' ./... )

printf "%b" "${NO_COLOR}"
